# Theme config
router: true

style:
  primary_color: "deep-purple"
  accent_color: "red"
  bg_color: "#eeeeee"
  hoverable: true

info:
  bg_image: /images/bg.jpg
  avatar: /images/avatar.png
  slogan: ""
  sns:
    Twitter:
      link: https://twitter.com
      fa: 'fa-twitter'
    Facebook:
      link: https://facebook.com
      null_icon: true

# HTML head
head:
  favicon: /images/avatar.png
  high_res_favicon: /images/avatar.png
  apple_touch_icon: /images/avatar.png
  keywords: rodbate, blog, java

# Search
search: true

# Post
post:
  entry_excerpt: 80
  random_pics: false
  qr_code: true
  prism:
    theme: xonokai
    line_number: true
  word_count: true
  read_time: true

share_menu:
  rss: true
  weibo: true
  twitter: true
  facebook: true
  googleplus: true
  linkedin: true
  qq: true
  telegram: true

pages:
  Github:
    link: "https://github.com/rodbate"
    type: 'internal'
    md: "&#xe0ba;"


# comment
comment:
    use: disqus
    shortname: rodbate

# footer
footer:
  since:
  ICP:
  image:
  last_updated:

# Service Worker
service_worker:

# scss
node_sass:
  debug: false
  outputStyle: compressed
  precision: 5
  sourceComments: false

# Vendors
vendors:
  style_min_css:
  outdatedbrowser_min_js:
  js_min_js:
  custom_head:
  custom_js:

debug: false